### PR TITLE
Added mvc 5-3 project and test.

### PR DESCRIPTION
**Pull request by Eonasdan**
Updated nuget packges, fixed some spelling, used c# 6 where available, general code clean up and most importantly removed unnecessary decencies.

### CODE REVIEW

**Comment by Eonasdan** [comment]
I have some powershell scripts that can automatically create nuget packages in case you're interested

**Comment by Eonasdan** [comment]
went ahead and published my own nuget package https://www.nuget.org/packages/ActionMailerNext.Mvc5-3/

**Comment by Eonasdan** [comment]
unfortunately, the fix to the From address added to my branch from @CheCoxshall is part of the core project which means I can't simply publish my nuget package to fix it. We'll have to wait for someone on the team to merge and update it (like maybe @stukalin ?).

**Comment by CheCoxshall** [comment]
Ah - may be an issue there as it's using the c# 6.0 safe navigation operator!

**Pull request closed without merging**
